### PR TITLE
Feature/searchbar experience

### PR DESCRIPTION
**Pull request by felixrindt**
This makes Enter basically do nothing in the search bar, as requested for #165

---
This change is [Reviewable](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/201)

### CODE REVIEW

**Review by Paulpanther — CHANGES_REQUESTED** [review]
Enter should not create a new line. Could you change that? Maybe catch enter beforehand

**Review by Paulpanther — APPROVED** [review]

**Review by Paulpanther — DISMISSED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/201)* status: all files reviewed, 1 unresolved discussion (waiting on @felixrindt)

*[a discussion](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/201#-LgcC8-fAgfCWRgIklFL:-LgcC8-g2Colg2CMngzN:ba56onj) (no related file):*
Enter should not create a new line. Could you change that? Maybe catch enter beforehand

---

**Review by martintaraz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/201)* status: all files reviewed, 1 unresolved discussion (waiting on @Paulpanther)

*[a discussion](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/201#-LgcC8-fAgfCWRgIklFL:-LgdjiCbAvQ2NcIhAvII:b-ytw96k) (no related file):*
<details><summary><i>Previously, Paulpanther (Paul Methfessel) wrote…</i></summary><blockquote>

Enter should not create a new line. Could you change that? Maybe catch enter beforehand
</blockquote></details>

This is fixed in the latest version

---

**Review by timgarrels — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/201)* status: all files reviewed, 1 unresolved discussion (waiting on @Paulpanther)

**Review by timgarrels — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/201)* status: all files reviewed, 1 unresolved discussion (waiting on @Paulpanther)

**Pull request merged**
