### PR TITLE
Bug133/fix update of emails

### LINKED ISSUE #133: Fix update of emails
So here are some issues with new update button...

- [x] folders within folders wont work --> make it recursive

- [x] mails are not refreshing as they should. Step to reproduce: 
go to HPI mail acccount >> inbox, send yourself a mail ,and press update. The new mail will only appear after you switched folder and open up the inbox again...
- [x]  fix ICLoadOlderMails... overwrite retrieve flags for ICLoadOlderMails
         ~(it somehow causes an Memory Overflow for nested folders....)~
- [x] fix flags
- [x] load mails without blocking ui

other points: (make a seperate issue for them)
- [ ] after using `update`-button i got a lot of weird messages in empty folders
image
https://stackoverflow.com/questions/29151325/phantom-messages-in-exchange-calendar-folder

- [ ] some folders wont be displayed including 'Sent Items'

- [ ] for my tonline mail account the `update` buttons works the first time, but the next time i selected the account i sometimes get an error message:
image

After some digging i found this Server Response, which caused the `ICEndpoint` to throw a Parameter Error
```* OK [CLOSED] Previous mailbox closed.' '. NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.000 + 0.000 secs).'```

### PR DESCRIPTION
**Pull request by davidhennemann**
This closes #133.

- [x] folders within folders wont work --> make it recursive

- [x] mails are not refreshing as they should. Step to reproduce: 
go to HPI mail acccount >> inbox, send yourself a mail ,and press update. The new mail will only appear after you switched folder and open up the inbox again...
- [x]  fix ICLoadOlderMails... overwrite retrieve flags for ICLoadOlderMails
- [x] fix flags
- [x] load mails without blocking ui

### CODE REVIEW

**Comment by mariwalt** [comment]
I noticed two things:
a) Openning an email does not work
b) Mark as Flag does not work (Flag is correctly set on the server, but not shown in the UI)

**Comment by davidhennemann** [comment]
@mariwalt Did you Update your squeak described as in #96?

**Comment by mariwalt** [comment]
?Ah, I forget it for this PC.

Opening emails works now :)

________________________________

**Comment by davidhennemann** [comment]
Okay, Flags should be working again.

**Comment by davidhennemann** [comment]
@ClayGee Want to take a look at it? Then we can merge sometimes soon :)

**Review by ClayGee — APPROVED** [review]
Amazing work dude <3. Did some minor code refactoring, deleted or added spaces and so on :).

**Pull request merged**
