### PR TITLE
bug123/Adjust ICFolder window size

### LINKED ISSUE #123: Fix horizontal scroll bar in e-mail window
Als User möchte ich nach links und rechts schrollen können im E-Mail Fenster.

### PR DESCRIPTION
**Pull request by ClayGee**
Please take a look at the IMAP window and if it works for you with the width and resizing. 
I will provide some pictures.

This closes #123

### CODE REVIEW

**Comment by ClayGee** [comment]
image

**Comment by davidhennemann** [comment]
image

So on my desktop its a little bit large :D and i cant make it smaller (ofc i can't, its one of the features^^). 
But I think we need to get some more details about the resolution. I think it looks fine on your Elementary OS (but **everything** else is also very tiny there). So your Implementation is fine, but we need to tune the values `extent: 1240 @ 600; minimumExtent: 1980 @ 600.`. Maybe we can add a function, which calculates this values for us. :)

**Review by davidhennemann — CHANGES_REQUESTED** [review]
So implementation is fine, values needs to be calculated dynamically. A beginning would be to ask for the current resolution within squeak. `Display width` will return the width and `Display height` the height. For my desktop its (`2560x1377`).  Now you can use these new values to calculate the size in percentage. I think because everything was so small within Squeak on Linux your Display has a very large resolution.

**Comment by davidhennemann** [comment]
Also please merge current develop to resolve merge conflicts :)

**Comment by ClayGee** [comment]
@davidhennemann Could you take a look at it again pls :3?

**Comment by davidhennemann** [comment]
I'll close this for the beginning until we figure out a smart way for figure out correct size. :(

**Pull request closed without merging**
