### PR TITLE
Incorporate Justus' coveralls setup to develop

### PR DESCRIPTION
**Pull request by felixrindt**
This change is [Reviewable](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/185)

### CODE REVIEW

**Comment by felixrindt** [comment]
I'm really confused by what the difference is with the Readme in master and develop. Could someone explain please?

**Comment by timgarrels** [comment]
I assume that the problem is with the travis and coverage badges.
The master README just shows travis build status and the coverage (which for some reason is displayed as "unknown", is that another issue?) and the develop README shows the master and develop status as well, next to the coverage.

Therefore I'd suggest to resolve the merge conflicts by keeping the old master README as a user does not need to know the status of the develop branch

**Comment by felixrindt** [comment]
I'd like to have the develop batch as well, because that's what I as a dev want to see.

**Comment by felixrindt** [comment]
I'd like to have the develop batch as well, because that's what I as a dev want to see.

**Pull request closed without merging**
